api/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'api.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

app/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from .api.resources import *
from .api.views import *

api_router = Api(api_name='v0')
api_router.register(InstitutionResource())
api_router.register(AccountResource())
api_router.register(CategoryResource())
api_router.register(BriefCategoryResource())
api_router.register(TransactionResource())
api_router.register(BriefTransactionResource())

urlpatterns = patterns('',
    url(r'', include('django.contrib.auth.urls')),
    #url(r'^admin/', include('admin.site.urls')),
    url(r'^api/?', include(api_router.urls)),
    url(r'^landing/?', TemplateView.as_view(template_name='landing.html'), name='landing'),
    url(r'^import/?', login_required(ImportFile), name='import'),
    url(r'^', login_required(Index), name='index'),
)

app/api/models.py
from django.db import models
from django.contrib.auth.models import User


class Institution(models.Model):

  name = models.TextField(blank=True)
  organization = models.TextField(blank=True)
  fid = models.TextField(unique=True)


class Account(models.Model):

  user = models.ForeignKey(User)
  account_id = models.TextField()
  routing_number = models.TextField()
  branch_id = models.TextField()
  account_type = models.TextField()
  institution = models.ForeignKey(Institution)
  type = models.SmallIntegerField(choices=(
    (0, 'Unknown'), (1, 'Bank'), (2, 'CreditCard'), (3, 'Investment'))
  )

  class Meta:
    unique_together = (('user', 'institution', 'account_id'))


class Category(models.Model):

  user = models.ForeignKey(User)
  name = models.TextField()
  parent = models.ForeignKey('self', blank=True, null=True, related_name='children')

  class Meta:
    unique_together = (('user', 'name'))


class Transaction(models.Model):

  # OFX fields
  account = models.ForeignKey(Account)
  fitid = models.TextField()
  payee = models.TextField(blank=True)
  type = models.TextField()
  date = models.DateTimeField()
  amount = models.DecimalField(max_digits=10, decimal_places=2)
  memo = models.TextField(blank=True)
  # Standard Industry Code
  sic = models.PositiveSmallIntegerField(blank=True, null=True)
  # Merchant Category Code
  mcc = models.PositiveSmallIntegerField(blank=True, null=True)
  checknum = models.PositiveSmallIntegerField(blank=True, null=True)

  # Other fields
  user = models.ForeignKey(User)
  category = models.ForeignKey(Category, blank=True, null=True)

  class Meta:
    unique_together = (('user', 'account', 'fitid'),)


class CategoryRule(models.Model):
  
  user = models.ForeignKey(User)
  category = models.ForeignKey(Category)
  term = models.TextField()

  class Meta:
    unique_together = (('user', 'category', 'term'),)

app/api/forms.py
from django import forms


class UploadFileForm(forms.Form):
  files  = forms.FileField(
    label="Select files"
  )

app/api/views.py
import json
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.forms.models import model_to_dict

from .parser import handle_uploaded_file
from .models import Category


def generate_category_tree(element):
  parent = model_to_dict(element[0])
  children = element[1].all()
  if children:
    parent['children'] = [generate_category_tree((c, c.children)) for c in children]
  return parent


def Index(request):
  categories = [(c, c.children) for c in Category.objects.filter(parent=None)]
  category_tree = [generate_category_tree(c) for c in categories]

  return render(request, 'index.html',
                dictionary={'categories': json.dumps(category_tree)})


def ImportFile(request):
  if request.method == 'POST':
    for f in request.FILES.getlist('files'):
      handle_uploaded_file(f, request.user)
    return HttpResponseRedirect('/import/')
  return render(request, 'import.html', dictionary={'categories': '[]'})

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="csrf-token" content="{{csrf_token}}" onload="setCSRF()">
  <title>{% block title %}JudoJournal{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <script type="text/javascript" src="{% static 'bower/modernizr/modernizr.js' %}"></script>
  {% block head %}
  {% endblock %}
</head>
<body>
  <div id="non-footer">
    <div id="page-container">
			<div class="contain-to-grid">
				<nav class="top-bar">
					<ul class="title-area">
						<li class="name">
							<h1><a href="{% url 'landing' %}">JudoJournal</a></h1>
						</li>
						<li class="toggle-topbar"><a><i class="fa fa-bars fa-2x"></i></a></li>
					</ul>

					<section class="top-bar-section">
						<!-- Right Nav Section -->
						<ul class="right">
							{% block main_menu_right %}
								{% if user.is_authenticated %}
									<li><a href="/profile"><i class="fa fa-user"></i> {{ user.username }}</a></li>
									<li><a href="/settings"><i class="fa fa-cog"></i> Settings</a></li>
									<li><a href="{% url 'django.contrib.auth.views.logout' %}?next=/"><i class="fa fa-sign-out"></i> Sign out</a></li>
								{% else %}
									<li><a href="{% url 'django.contrib.auth.views.login' %}"><i class="fa fa-sign-in"></i> Sign in</a></li>
								{% endif %}
							{% endblock %}
						</ul>
						<!-- Left Nav Section -->
						<ul class="left">
							{% block main_menu_left %}
							{% endblock %}
						</ul>
					</section>
				</nav>
			</div>

      <div id="content">
      {% block content %}{% endblock %}
      </div>
    </div><!--/page-container -->
  </div><!--/non-footer -->
  
  <footer>
    <div class="row">
      <div class="small-12 columns">
        {% block footer %}
        {% endblock %}
      </div>
    </div>
  </footer>
  
  <script type="text/javascript" src="{% static 'bower/jquery/dist/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bower/fastclick/lib/fastclick.js' %}"></script>
  <script type="text/javascript">
    $(function() {
      // Foundation menu
      $(".toggle-topbar").click(function() {
          $(".top-bar").toggleClass("expanded");
      });
      // fastclick
      FastClick.attach(document.body);
    });
  </script>
  <script type="text/javascript">
    // Set global variables
    var GLOBAL = {};
    GLOBAL.djangoUser = false;
    {% if user.is_authenticated %}
      GLOBAL.djangoUser = {
        username: "{{ user.username }}",
      };
    {% endif %}
    GLOBAL.categories = JSON.parse('{{ categories|safe }}');
  </script>
  {% block js %}
  {% endblock %}
</body>
</html>

templates/import.html
{% extends "single_page_form.html" %}

{% block header %}
  <div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="{% url 'index' %}">JudoJournal</a></h1>
        </li>
      </ul>
    </nav>
  </div>
{% endblock %}

{% block form %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <p><label for="id_files">Select files:</label> <input id="id_files" name="files" type="file" multiple></p>
  <button type="submit" class="expand">Import</button>
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
{% endblock %}

{% block content %}
{% endblock %}

{% block js %}
  <script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
  <script type="text/javascript" src="{% static 'bower/underscore/underscore.js' %}"></script>
  <script type="text/javascript" src="{% static 'bower/backbone/backbone.js' %}"></script>
  <script type="text/javascript" src="{% static 'bower/marionette/lib/backbone.marionette.js' %}"></script>
  <script type="text/javascript" src="{% static 'libs/handlebars-1.3.0.runtime.js' %}"></script>

  <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/overrides.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/models.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/templates.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/views.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/routes.js' %}"></script>
{% endblock %}

templates/landing.html
{% extends "base.html" %}
{% load staticfiles %}

templates/single_page_form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="small-centered small-12 medium-6 large-4 columns">
    <div class="single-page-form">
    {% block form%}
    {% endblock %}
    </div>
  </div>

</div>
{% endblock %}

{% block js %}
{% endblock %}